# Generated by Django 3.1 on 2020-08-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(verbose_name='')),
                ('title', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('title', models.TextField()),
                ('summery', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_feed.channel')),
            ],
        ),
    ]
