# Generated by Django 3.1 on 2020-08-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='address',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
