# Generated by Django 3.1 on 2020-08-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0002_auto_20200820_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='published_date',
            new_name='published_datetime',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='guid',
        ),
    ]
