# Generated by Django 3.1 on 2020-08-20 18:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss_feed', '0002_auto_20200820_1413'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchannel',
            unique_together={('user', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='userfeeditem',
            unique_together={('user', 'feed_item')},
        ),
    ]
