# Generated by Django 3.1 on 2020-08-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0003_auto_20200821_0636'),
        ('collection', '0002_auto_20200820_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeeditem',
            name='feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_item_ufi', to='rss_feed.feeditem'),
        ),
    ]
